import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { RefreshCcw, LayoutGrid, Dices } from 'lucide-react';

export function GeomancyCaster() {
  const { t } = useTranslation();
  const [figures, setFigures] = useState<number[][]>([]);

  // Geomancy involves 16 figures generated by 4 binary lines
  // Generating 4 mother figures randomly
  const castMothers = () => {
    const mothers = [];
    for (let i = 0; i < 4; i++) {
       const figure = [];
       for (let j = 0; j < 4; j++) {
         // 1 (single dot) or 2 (double dots)
         figure.push(Math.random() > 0.5 ? 1 : 2);
       }
       mothers.push(figure);
    }
    
    // In actual Raml, we would calculate the daughters, nieces, witnesses, and judge.
    // For demo, we just generate the 4 mothers.
    
    setFigures(mothers);
  };

  const clear = () => setFigures([]);

  return (
    <div className="flex flex-col gap-8 bg-white dark:bg-gray-950 p-6 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 max-w-2xl mx-auto w-full">
      <div className="flex justify-between items-center border-b border-gray-100 dark:border-gray-900 pb-4">
         <h2 className="text-lg font-bold flex items-center gap-2 text-violet-700 dark:text-violet-500">
            <LayoutGrid className="w-5 h-5" />
            {t('GeomancyCaster')}
         </h2>
         <button 
           onClick={clear}
           className="p-2 text-gray-400 hover:text-violet-600 rounded-full transition-colors"
         >
           <RefreshCcw className="w-5 h-5" />
         </button>
      </div>

      {figures.length === 0 ? (
         <div className="flex flex-col items-center justify-center py-12 gap-6">
           <Dices className="w-16 h-16 text-gray-300 dark:text-gray-700" />
           <p className="text-gray-500 text-center max-w-md">
             Générez les 4 figures mères (Oumahat) de la géomancie (Raml) par tirage aléatoire binaire.
           </p>
           <button 
             onClick={castMothers}
             className="px-8 py-4 bg-violet-600 hover:bg-violet-700 text-white rounded-xl font-bold shadow-lg shadow-violet-200 dark:shadow-none transition-all active:scale-95"
           >
              Lancer le Tirage (Darb)
           </button>
         </div>
      ) : (
         <div className="flex flex-col items-center gap-8">
            <div className="flex gap-8" dir="rtl">
               {figures.map((fig, idx) => (
                  <div key={idx} className="flex flex-col items-center gap-2">
                     <span className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Mère {idx + 1}</span>
                     <div className="flex flex-col gap-2 p-4 border border-violet-200 dark:border-violet-900 bg-violet-50 dark:bg-violet-900/20 rounded-xl">
                        {fig.map((dots, lineIdx) => (
                           <div key={lineIdx} className="flex justify-center gap-2 h-4 w-12">
                              {dots === 1 ? (
                                 <div className="w-3 h-3 rounded-full bg-violet-800 dark:bg-violet-400"></div>
                              ) : (
                                 <>
                                   <div className="w-3 h-3 rounded-full bg-violet-800 dark:bg-violet-400"></div>
                                   <div className="w-3 h-3 rounded-full bg-violet-800 dark:bg-violet-400"></div>
                                 </>
                              )}
                           </div>
                        ))}
                     </div>
                  </div>
               ))}
            </div>

            <div className="w-full bg-gray-50 dark:bg-gray-900 p-6 rounded-xl border border-gray-100 dark:border-gray-800 mt-4 text-center">
               <p className="text-gray-600 dark:text-gray-400">
                  L'algorithme complet génère les 16 figures du thème géomantique (filles, nièces, témoins, juge) à partir de ces 4 mères par addition binaire.
               </p>
            </div>
            
            <button 
             onClick={castMothers}
             className="px-6 py-3 border border-violet-200 text-violet-700 hover:bg-violet-50 dark:border-violet-800 dark:text-violet-400 dark:hover:bg-violet-900/50 rounded-xl font-bold transition-all"
            >
              Nouveau Tirage
            </button>
         </div>
      )}
    </div>
  );
}
